name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  # push: {branches: ["master", "main"]}
  push:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment:
      name: production
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          # Configure base content:
          # https://github.com/lowlighter/metrics/blob/master/source/plugins/base/README.md
          base: activity
          base_indepth: yes

          # Configure Isometric Commit Calendar plugin:
          # https://github.com/lowlighter/metrics/blob/master/source/plugins/isocalendar/README.md
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year

          # Configure Languages activity plugin:
          # https://github.com/lowlighter/metrics/blob/master/source/plugins/languages/README.md
          plugin_languages: yes
          plugin_languages_details: percentage, lines
          plugin_languages_indepth: no
          plugin_languages_sections: recently-used
          plugin_languages_analysis_timeout: 60
          plugin_languages_recent_categories: programming, markup, prose
          plugin_languages_recent_load: 5000
          plugin_languages_recent_days: 90
